language: cpp
dist: trusty
sudo: true

env:
  - PKG_CONFIG_PATH=${HOME}/.local/share/pkgconfig:${HOME}/.local/lib/pkgconfig/

addons:
  apt:
    packages:
       - libcogl-dev
       - libclutter-1.0-dev
       #- mm-common
       #- cluttermm
       - libgtkmm-2.4-dev

before_install:
  - sudo apt-get install clutter-1.0 -y
  - sudo apt-get install pangomm-1.4 -y
  - sudo apt-get install atkmm-1.6 -y
  - sudo apt-get install libxml-parser-perl -y

compiler:
  - gcc
  - clang

before_script:
  - ./install-mm-common.sh
  - export PATH="${PATH}:${HOME}/.local/bin"
  - ./install-cluttermm.sh

#script:
#  - cmake .
#  - make
