language: cpp
dist: trusty
sudo: true

addons:
  apt:
    packages:
       - libcogl-dev
       - libclutter-1.0-dev
       #- mm-common
       #- cluttermm
       - libgtkmm-2.4-dev

before_install:
  - sudo apt-get install clutter-1.0 -y

compiler:
  - gcc
  - clang

before_script:
  - ./install-mm-common.sh
  - export PATH="${PATH}:${HOME}/.local/bin"
  - ./install-cluttermm.sh

script:
  - cmake .
  - make
